[package]
name = "mir-sys"
version = "0.1.0"
edition = "2021"
links = "mir"

[build-dependencies]
cc = "1.0"
bindgen = "0.69"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "android")'.dependencies]
android_log-sys = "0.3"

[dev-dependencies]
libc = "0.2"
